module.exports = {
  apps: [
    {
      name: "dev-user-service",
      script: "./backend/user-service/bin/user-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9001,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_user_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.user.events",
        KAFKA_GROUP_ID: "dev-user-service-consumer",
        CONFIG_PATH: "./backend/user-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        BOOKING_KAFKA_TOPIC: "dev.booking.events"
      }
    },
    {
      name: "dev-core-service",
      script: "./backend/core-service/bin/core-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9002,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_core_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.core.events",
        KAFKA_GROUP_ID: "dev-core-service-consumer",
        CONFIG_PATH: "./backend/core-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        GIN_MODE: "debug"
      }
    },
    {
      name: "dev-booking-service",
      script: "./backend/booking-service/bin/booking-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9003,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_booking_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.booking.events",
        KAFKA_GROUP_ID: "dev-booking-service-consumer",
        CONFIG_PATH: "./backend/booking-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        USER_SERVICE_URL: "http://127.0.0.1:9001",
        CORE_SERVICE_URL: "http://127.0.0.1:9002",
        PAYMENT_KAFKA_TOPIC: "dev.payment.events"
      }
    },
    {
      name: "dev-payment-service",
      script: "./backend/payment-service/bin/payment-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9004,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_payment_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.payment.events",
        CONFIG_PATH: "./backend/payment-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        PAYMENT_GATEWAY: "pakasir",
        PAKASIR_SLUG: "drive-master-indonesia-dev",
        PAKASIR_API_KEY: "vJBTSyuJxhwp9Yc8A28EhM84GSOMDRh9",
        PAKASIR_FRONTEND_URL: "https://dev.drivemaster.id",
        DOKU_CLIENT_ID: "BRN-0236-1782979927158",
        DOKU_SECRET_KEY: "SK-FX43zADxdeDIOLEJ8dff",
        DOKU_BASE_URL: "https://api-sandbox.doku.com",
        DOKU_NOTIFICATION_URL: "http://localhost:8088/api/v1/payments/doku/notification",
        DOKU_FRONTEND_URL: "http://localhost:3000",
        BOOKING_SERVICE_URL: "http://127.0.0.1:9003",
        CORE_SERVICE_URL: "http://127.0.0.1:9002",
        USER_SERVICE_URL: "http://127.0.0.1:9001"
      }
    },
    {
      name: "dev-api-gateway",
      script: "./backend/api-gateway/bin/api-gateway",
      cwd: "/var/www/drive",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        SERVER_PORT: 9088,
        SERVER_MODE: "debug",
        CONFIG_PATH: "./backend/api-gateway/pkg/config/config.yaml",
        USER_SERVICE_URL: "http://127.0.0.1:9001",
        CORE_SERVICE_URL: "http://127.0.0.1:9002",
        BOOKING_SERVICE_URL: "http://127.0.0.1:9003",
        PAYMENT_SERVICE_URL: "http://127.0.0.1:9004"
      }
    },
    {
      name: "dev-drive-frontend",
      script: "./frontend/.output/server/index.mjs",
      cwd: "/var/www/drive",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        NODE_OPTIONS: "--max-old-space-size=256",
        PORT: 3001,
        NUXT_PUBLIC_API_BASE: "https://api-dev.drivemaster.id/api/v1",
        NUXT_PUBLIC_API_BASE_URL: "https://api-dev.drivemaster.id/api/v1",
        NUXT_PUBLIC_USER_API_BASE: "https://api-dev.drivemaster.id/api/v1/users",
        NUXT_PUBLIC_CORE_API_BASE: "https://api-dev.drivemaster.id/api/v1/core",
        NUXT_PUBLIC_BOOKING_API_BASE: "https://api-dev.drivemaster.id/api/v1/bookings",
        NUXT_PUBLIC_MODE: "dev",
        NUXT_PUBLIC_GA_MEASUREMENT_ID: "G-1SR8F1H6D9",
        NUXT_PUBLIC_GA_PROPERTY_ID: "G-539969879"
      }
    }
  ]
};
