module.exports = {
  apps: [
    {
      name: "dev-user-service",
      script: "./backend/user-service/bin/user-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9001,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_user_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9093",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.user.events",
        KAFKA_GROUP_ID: "dev-user-service-consumer",
        CONFIG_PATH: "./backend/user-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true"
      }
    },
    {
      name: "dev-core-service",
      script: "./backend/core-service/bin/core-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9002,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_core_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9093",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.core.events",
        KAFKA_GROUP_ID: "dev-core-service-consumer",
        CONFIG_PATH: "./backend/core-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        GIN_MODE: "debug"
      }
    },
    {
      name: "dev-booking-service",
      script: "./backend/booking-service/bin/booking-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9003,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_booking_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9093",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.booking.events",
        KAFKA_GROUP_ID: "dev-booking-service-consumer",
        CONFIG_PATH: "./backend/booking-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true",
        USER_SERVICE_URL: "http://127.0.0.1:9001",
        CORE_SERVICE_URL: "http://127.0.0.1:9002"
      }
    },
    {
      name: "dev-payment-service",
      script: "./backend/payment-service/bin/payment-service",
      cwd: "/var/www/drive",
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 9004,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "dev_drivemaster_payment_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        REDIS_DB: "1",
        KAFKA_BROKERS: "127.0.0.1:9093",
        KAFKA_ENABLED: "true",
        KAFKA_TOPIC: "dev.payment.events",
        CONFIG_PATH: "./backend/payment-service/pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "true"
      }
    },
    {
      name: "dev-api-gateway",
      script: "./backend/api-gateway/bin/api-gateway",
      cwd: "/var/www/drive",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        SERVER_PORT: 9088,
        SERVER_MODE: "debug",
        CONFIG_PATH: "./backend/api-gateway/pkg/config/config.yaml",
        USER_SERVICE_URL: "http://127.0.0.1:9001",
        CORE_SERVICE_URL: "http://127.0.0.1:9002",
        BOOKING_SERVICE_URL: "http://127.0.0.1:9003"
      }
    }
  ]
};
