const path = require("path");

module.exports = {
  apps: [
    {
      name: "user-service",
      script: "./bin/user-service",
      cwd: path.join(__dirname, "backend/user-service"),
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 8001,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "drivemaster_user_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "false",
        KAFKA_TOPIC: "user.events",
        KAFKA_GROUP_ID: "user-service-consumer",
        CONFIG_PATH: "./pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "false",
        BOOKING_KAFKA_TOPIC: "booking.events"
      }
    },
    {
      name: "core-service",
      script: "./bin/core-service",
      cwd: path.join(__dirname, "backend/core-service"),
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 8002,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "drivemaster_core_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "false",
        KAFKA_TOPIC: "core.events",
        KAFKA_GROUP_ID: "core-service-consumer",
        CONFIG_PATH: "./pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "false",
        GIN_MODE: "release"
      }
    },
    {
      name: "booking-service",
      script: "./bin/booking-service",
      cwd: path.join(__dirname, "backend/booking-service"),
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 8003,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "drivemaster_booking_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "false",
        KAFKA_TOPIC: "booking.events",
        KAFKA_GROUP_ID: "booking-service-consumer",
        CONFIG_PATH: "./pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "false",
        USER_SERVICE_URL: "http://127.0.0.1:8001",
        CORE_SERVICE_URL: "http://127.0.0.1:8002",
        PAYMENT_KAFKA_TOPIC: "payment.events"
      }
    },
    {
      name: "payment-service",
      script: "./bin/payment-service",
      cwd: path.join(__dirname, "backend/payment-service"),
      args: "serve",
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        PORT: 8004,
        POSTGRES_HOST: "127.0.0.1",
        POSTGRES_PORT: 5432,
        POSTGRES_USER: "admin_drive",
        POSTGRES_PASSWORD: "drivemaster123",
        POSTGRES_DB: "drivemaster_payment_service",
        REDIS_HOST: "127.0.0.1",
        REDIS_PORT: 6379,
        REDIS_PASSWORD: "",
        KAFKA_BROKERS: "127.0.0.1:9092",
        KAFKA_ENABLED: "false",
        KAFKA_TOPIC: "payment.events",
        KAFKA_GROUP_ID: "payment-service-consumer",
        CONFIG_PATH: "./pkg/config/config.yaml",
        RUN_MIGRATIONS: "true",
        RUN_SEEDERS: "false",
        PAYMENT_GATEWAY: "pakasir",
        PAKASIR_SLUG: "drive-master-indonesia-dev",
        PAKASIR_API_KEY: "vJBTSyuJxhwp9Yc8A28EhM84GSOMDRh9",
        PAKASIR_FRONTEND_URL: "https://drivemaster.id",
        DOKU_CLIENT_ID: "BRN-0226-1782972609555",
        DOKU_SECRET_KEY: "SK-OdJ7OYT6G5nGW2HLs0b6",
        DOKU_BASE_URL: "https://api.doku.com",
        DOKU_NOTIFICATION_URL: "https://drivemaster.id/api/v1/payments/doku/notification",
        DOKU_FRONTEND_URL: "https://drivemaster.id",
        BOOKING_SERVICE_URL: "http://127.0.0.1:8003",
        CORE_SERVICE_URL: "http://127.0.0.1:8002",
        USER_SERVICE_URL: "http://127.0.0.1:8001"
      }
    },
    {
      name: "api-gateway",
      script: "./bin/api-gateway",
      cwd: path.join(__dirname, "backend/api-gateway"),
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        SERVER_PORT: 8088,
        SERVER_MODE: "release",
        CONFIG_PATH: "./pkg/config/config.yaml",
        USER_SERVICE_URL: "http://127.0.0.1:8001",
        CORE_SERVICE_URL: "http://127.0.0.1:8002",
        BOOKING_SERVICE_URL: "http://127.0.0.1:8003",
        PAYMENT_SERVICE_URL: "http://127.0.0.1:8004"
      }
    },
    {
      name: "drive-frontend",
      script: "./.output/server/index.mjs",
      cwd: __dirname,
      instances: 1,
      autorestart: true,
      watch: false,
      env: {
        NODE_OPTIONS: "--max-old-space-size=256",
        PORT: 3000,
        NUXT_PUBLIC_API_BASE: "http://localhost:8088/api/v1",
        NUXT_PUBLIC_API_BASE_URL: "http://localhost:8088/api/v1",
        NUXT_PUBLIC_USER_API_BASE: "http://localhost:8088/api/v1/users",
        NUXT_PUBLIC_CORE_API_BASE: "http://localhost:8088/api/v1/core",
        NUXT_PUBLIC_BOOKING_API_BASE: "http://localhost:8088/api/v1/bookings",
        NUXT_PUBLIC_MODE: "dev",
        NUXT_PUBLIC_GA_MEASUREMENT_ID: "G-1SR8F1H6D9",
        NUXT_PUBLIC_GA_PROPERTY_ID: "G-539969879"
      }
    }
  ]
};
