package seeders

import (
	"core-service/models"
	"time"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// RunPackageSeeder seeds sample package data with features
func RunPackageSeeder(db *gorm.DB) error {
	packages := []models.Package{
		// 6 session packages (bronze)
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111101"),
			Name:            "6x",
			Description:     "6 training sessions with SIM A certification",
			PackageType:     models.PackageTypeBronze,
			Price:           1500000,
			DiscountPrice:   1350000,
			DurationMinutes: 90,
			TotalSessions:   6,
			Features:        []string{"Free Trial", "6 training sessions", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111102"),
			Name:            "6x + Night Session",
			Description:     "6 training sessions including night driving with SIM A certification",
			PackageType:     models.PackageTypeBronze,
			Price:           1750000,
			DiscountPrice:   1600000,
			DurationMinutes: 90,
			TotalSessions:   6,
			Features:        []string{"Free Trial", "6 training sessions", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111103"),
			Name:            "6x + Weekend Session",
			Description:     "6 training sessions including weekend sessions with SIM A certification",
			PackageType:     models.PackageTypeBronze,
			Price:           1850000,
			DiscountPrice:   1700000,
			DurationMinutes: 90,
			TotalSessions:   6,
			Features:        []string{"Free Trial", "6 training sessions", "Weekend Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111104"),
			Name:            "6x + Weekend & Night Session",
			Description:     "6 training sessions including weekend and night sessions with SIM A certification",
			PackageType:     models.PackageTypeBronze,
			Price:           1950000,
			DiscountPrice:   1750000,
			DurationMinutes: 90,
			TotalSessions:   6,
			Features:        []string{"Free Trial", "6 training sessions", "Weekend Session", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		// 8 session packages (silver)
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111201"),
			Name:            "8x",
			Description:     "8 training sessions with SIM A certification",
			PackageType:     models.PackageTypeSilver,
			Price:           1950000,
			DiscountPrice:   1750000,
			DurationMinutes: 90,
			TotalSessions:   8,
			Features:        []string{"Free Trial", "8 training sessions", "SIM A"},
			Highlight:       true,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111202"),
			Name:            "8x + Night Session",
			Description:     "8 training sessions including night driving with SIM A certification",
			PackageType:     models.PackageTypeSilver,
			Price:           2100000,
			DiscountPrice:   1900000,
			DurationMinutes: 90,
			TotalSessions:   8,
			Features:        []string{"Free Trial", "8 training sessions", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111203"),
			Name:            "8x + Weekend Session",
			Description:     "8 training sessions including weekend sessions with SIM A certification",
			PackageType:     models.PackageTypeSilver,
			Price:           2100000,
			DiscountPrice:   1900000,
			DurationMinutes: 90,
			TotalSessions:   8,
			Features:        []string{"Free Trial", "8 training sessions", "Weekend Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111204"),
			Name:            "8x + Weekend & Night Session",
			Description:     "8 training sessions including weekend and night sessions with SIM A certification",
			PackageType:     models.PackageTypeSilver,
			Price:           2250000,
			DiscountPrice:   2050000,
			DurationMinutes: 90,
			TotalSessions:   8,
			Features:        []string{"Free Trial", "8 training sessions", "Weekend Session", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		// 10 session packages (gold)
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111301"),
			Name:            "10x",
			Description:     "10 training sessions with SIM A certification",
			PackageType:     models.PackageTypeGold,
			Price:           2250000,
			DiscountPrice:   2050000,
			DurationMinutes: 90,
			TotalSessions:   10,
			Features:        []string{"Free Trial", "10 training sessions", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111302"),
			Name:            "10x + Night Session",
			Description:     "10 training sessions including night driving with SIM A certification",
			PackageType:     models.PackageTypeGold,
			Price:           2450000,
			DiscountPrice:   2250000,
			DurationMinutes: 90,
			TotalSessions:   10,
			Features:        []string{"Free Trial", "10 training sessions", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111303"),
			Name:            "10x + Weekend Session",
			Description:     "10 training sessions including weekend sessions with SIM A certification",
			PackageType:     models.PackageTypeGold,
			Price:           2450000,
			DiscountPrice:   2250000,
			DurationMinutes: 90,
			TotalSessions:   10,
			Features:        []string{"Free Trial", "10 training sessions", "Weekend Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111304"),
			Name:            "10x + Weekend & Night Session",
			Description:     "10 training sessions including weekend and night sessions with SIM A certification",
			PackageType:     models.PackageTypeGold,
			Price:           2650000,
			DiscountPrice:   2450000,
			DurationMinutes: 90,
			TotalSessions:   10,
			Features:        []string{"Free Trial", "10 training sessions", "Weekend Session", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		// 12 session packages (platinum)
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111401"),
			Name:            "12x",
			Description:     "12 training sessions with SIM A certification",
			PackageType:     models.PackageTypePlatinum,
			Price:           2650000,
			DiscountPrice:   2450000,
			DurationMinutes: 90,
			TotalSessions:   12,
			Features:        []string{"Free Trial", "12 training sessions", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111402"),
			Name:            "12x + Night Session",
			Description:     "12 training sessions including night driving with SIM A certification",
			PackageType:     models.PackageTypePlatinum,
			Price:           2900000,
			DiscountPrice:   2650000,
			DurationMinutes: 90,
			TotalSessions:   12,
			Features:        []string{"Free Trial", "12 training sessions", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111403"),
			Name:            "12x + Weekend Session",
			Description:     "12 training sessions including weekend sessions with SIM A certification",
			PackageType:     models.PackageTypePlatinum,
			Price:           2900000,
			DiscountPrice:   2650000,
			DurationMinutes: 90,
			TotalSessions:   12,
			Features:        []string{"Free Trial", "12 training sessions", "Weekend Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
		{
			ID:              uuid.MustParse("11111111-1111-1111-1111-111111111404"),
			Name:            "12x + Weekend & Night Session",
			Description:     "12 training sessions including weekend and night sessions with SIM A certification",
			PackageType:     models.PackageTypePlatinum,
			Price:           3150000,
			DiscountPrice:   2900000,
			DurationMinutes: 90,
			TotalSessions:   12,
			Features:        []string{"Free Trial", "12 training sessions", "Weekend Session", "Night Session", "SIM A"},
			Highlight:       false,
			Status:          models.PackageStatusActive,
			ImageURL:        "",
			CreatedAt:       time.Now(),
			UpdatedAt:       time.Now(),
		},
	}

	// Create or update all packages
	for _, p := range packages {
		result := db.Where("id = ?", p.ID).FirstOrCreate(&p)
		if result.Error != nil {
			return result.Error
		}
	}

	return nil
}
