package seeders

import (
	"time"

	"user-service/models"

	"github.com/google/uuid"
	"gorm.io/gorm"
)

// TestimonialSeeder seeds sample testimonials
type TestimonialSeeder struct {
	db *gorm.DB
}

func NewTestimonialSeeder(db *gorm.DB) *TestimonialSeeder {
	return &TestimonialSeeder{db: db}
}

// Seed inserts sample testimonials into the database
func (s *TestimonialSeeder) Seed() error {
	// Get admin user ID for AddedBy field
	var adminUser models.User
	if err := s.db.Where("role_id = ?", 4).First(&adminUser).Error; err != nil {
		// Fallback to first admin user if role_id lookup fails
		s.db.Where("username = ?", "admin").First(&adminUser)
	}
	addedBy := adminUser.ID
	if addedBy == uuid.Nil {
		addedBy = uuid.MustParse("00000000-0000-0000-0000-000000000001")
	}

	// Testimonials data - ID will be auto-generated by GORM
	testimonials := []models.Testimonial{
		{
			UserID:      uuid.MustParse("433c4e17-83cb-4133-a4ab-7abaef8a3afe"),
			Content:     "Pelayanan sangat memuaskan! Instruktur berpengalaman dan sabar dalam mengajar. Saya yang awalnya tidak bisa sama sekali, sekarang sudah bisa mengemudi dengan percaya diri. Kursus 12 sesi ini sangat worth it!",
			Rating:      5.0,
			Tags:        "satisfied,recommended,professional",
			Status:      models.TestimonialStatusPublished,
			IsFeatured:  true,
			AddedBy:     addedBy,
			AddedAt:     time.Now().AddDate(0, -1, 0),
			SortOrder:   1,
		},
		{
			UserID:      uuid.MustParse("86f5e950-cedb-495b-9528-48a7dffa6919"),
			Content:     "Sudah lulus ujian SIM A berkat Drive! Metode pengajaran modern dan kendaraan yang terawat. Night session juga sangat membantu karena saya pekerja shift. Highly recommended!",
			Rating:      5.0,
			Tags:        "graduated,night-session,shift-worker",
			Status:      models.TestimonialStatusPublished,
			IsFeatured:  true,
			AddedBy:     addedBy,
			AddedAt:     time.Now().AddDate(0, 0, -15),
			SortOrder:   2,
		},
	}

	// Fetch user data and create testimonials
	for i := range testimonials {
		// Fetch user details
		var user models.User
		if err := s.db.Where("id = ?", testimonials[i].UserID).First(&user).Error; err != nil {
			// Skip if user not found
			continue
		}

		// Populate user info
		testimonials[i].UserName = user.FirstName + " " + user.LastName
		testimonials[i].UserImage = user.Image
		testimonials[i].UserRole = "Member"

		// Check if testimonial already exists for this user
		var existing models.Testimonial
		if err := s.db.Where("user_id = ?", testimonials[i].UserID).First(&existing).Error; err == nil {
			// Testimonial already exists for this user, skip
			continue
		}

		// Create testimonial
		if err := s.db.Create(&testimonials[i]).Error; err != nil {
			return err
		}
	}

	return nil
}
